name: Deploy to GitHub Pages
on:
  push:
    branches:
      - fix/bug_workflow
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: Env 
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Build
      run: |
        npm install
        npm run-script build
      env:
        VITE_EMAIL_TEMPLATE_ID: ${{ secrets.VITE_EMAIL_TEMPLATE_ID }}
        VITE_EMAIL_USER_ID: ${{ secrets.VITE_EMAIL_USER_ID }}
        VITE_EMAIL_SERVICE_ID: ${{ secrets.VITE_EMAIL_SERVICE_ID }}
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: fix/bug_workflow
        folder: dist
        token: ${{ secrets.DEPLOY_TOKEN }}
